home/urls.py
from django.conf.urls import url

from . import views

app_name = 'home'

urlpatterns = [
    url(r'^homepage/$', views.homepage, name='homepage'),
    url(r'^guidance/$', views.guidance, name='guidance'),
    url(r'^team/$', views.team, name='team'),
]

manage_event/urls.py
from django.conf.urls import url
from . import views

app_name = 'manage_event'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^organize/$', views.organize_index, name='organize_index'),
    url(r'^participate/$', views.participate_index, name='participate_index'),

    url(r'^(?P<event_id>[0-9]+)/notification_redirect/(?P<notification_id>[0-9]+)/$', views.notification_redirect, name='notification_redirect'),
    url(r'^(?P<event_id>[0-9]+)/on_going/$', views.on_going, name='on_going'),
    url(r'^(?P<event_id>[0-9]+)/pending/$', views.pending, name='pending'),

    url(r'^(?P<event_id>[0-9]+)/make_decision/$', views.make_decision, name='make_decision'),
    url(r'^(?P<event_id>[0-9]+)/make_decision_render/$', views.make_decision_render, name='make_decision_render'),
    url(r'^(?P<event_id>[0-9]+)/make_decision_results/$', views.make_decision_results, name='make_decision_results'),
    url(r'^(?P<event_id>[0-9]+)/make_decision_detail/$', views.make_decision_detail, name='make_decision_detail'),
    url(r'^(?P<event_id>[0-9]+)/show_decision_result/$', views.show_decision_result, name='show_decision_result'),
    url(r'^(?P<event_id>[0-9]+)/abort_event_detail/$', views.abort_event_detail, name='abort_event_detail'),
    url(r'^(?P<event_id>[0-9]+)/abort_event_result/$', views.abort_event_result, name='abort_event_result'),
    url(r'^(?P<event_id>[0-9]+)/modify_event_deadline_detail/$', views.modify_event_deadline_detail, name='modify_event_deadline_detail'),
    url(r'^(?P<event_id>[0-9]+)/modify_event_deadline_result/$', views.modify_event_deadline_result, name='modify_event_deadline_result'),

    url(r'^create_event/$', views.create_event, name='create_event'),
    url(r'^(?P<event_id>[0-9]+)/create_publish/$', views.create_publish, name='create_publish'),
    url(r'^(?P<event_id>[0-9]+)/select_timeslots/$', views.select_timeslots, name='select_timeslots'),
    url(r'^(?P<event_id>[0-9]+)/modify_timeslots/$', views.modify_timeslots, name='modify_timeslots'),
    url(r'^profile/$', views.update_profile),
    url(r'^logout/$', views.webLogout),
    url(r'^(?P<event_id>[0-9]+)/select_publish/$', views.select_publish, name="select_publish"),
    url(r'^(?P<event_id>[0-9]+)/modify_timeslots_read/$', views.modify_timeslots_read, name="modify_timeslots_read"),
    url(r'^(?P<event_id>[0-9]+)/read_timeslots/$', views.read_timeslots, name='read_timeslots'),


    url(r'^(?P<event_id>[0-9]+)/make_decision_json/$', views.make_decision_json, name='make_decision_json'),

    url(r'^(?P<event_id>[0-9]+)/initialize_timeslots/$', views.initialize_timeslots, name='initialize_timeslots'),
    url(r'^(?P<event_id>[0-9]+)/modify_timeslots_update/$', views.modify_timeslots_update, name='modify_timeslots_update'),
    url(r'^(?P<event_id>[0-9]+)/select_publish_render/$', views.select_publish_render, name="select_publish_render"),
    url(r'^accept_invitation/(?P<key>\w+)/$', views.accept_invitation, name="accept_invitation"),
    url(r'^decline_invitation/(?P<key>\w+)/$', views.decline_invitation, name="decline_invitation"),

]

mysite/urls.py
import notifications.urls
from django.conf.urls import include, url
from django.contrib import admin
from home import views

urlpatterns = [
    url(r'^manage_event/', include('manage_event.urls')),
    url(r'^admin/', admin.site.urls),
    # This is our homepage!
    url(r'^$', views.homepage),
    url(r'^home/', include('home.urls')),
    url(r'^account/', include('social_django.urls', namespace='social')),
    url(r'^account/', include('django.contrib.auth.urls', namespace='auth')),
    url(r'^inbox/notifications/', include(notifications.urls, namespace='notifications')),

]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render


def homepage(request):
    return render(request, 'home/homepage.html')


def guidance(request):
    return render(request, 'home/guidance.html')


def team(request):
    return render(request, 'home/team.html')

home/templates/home/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Time2Meeting - Scheduling Web Application</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'home/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{% static 'home/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'home/vendor/simple-line-icons/css/simple-line-icons.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- Custom styles for this template -->
    <link href="{% static 'home/css/landing-page.min.css' %}" rel="stylesheet">

  </head>

  <body>
  <style type="text/css" media="screen">
  .right {
      text-align: right;
      float: right;
      margin-right: 10px;
  }
  .button-color{
      color:#FFF;
      background-color: #7386D5;
      border-color: #7386D5;
      }
  .name-color{
      }
  #ourHeading {
      font-size: 30px;
  }
  </style>
    <!-- Navigation -->
    <nav class="navbar navbar-light bg-light static-top">
      <div class="container">

        {% if user.is_authenticated %}
        <a class="navbar-brand" href="{% url 'manage_event:index' %}">Time2Meeting</a>
        {% load notifications_tags %}
          {% load static %}
          <script src="{% static 'notifications/js/notify.js' %}" type="text/javascript"></script>
          {% register_notify_callbacks callbacks='fill_notification_list,fill_notification_badge' %}
          <a class="right" href="/manage_event/">{% live_notify_badge classes="badge"%}</a>
          <a class="btn btn-primary" href="/manage_event/logout">Log out</a>

        {% else %}
          <a class="navbar-brand" href="{% url 'home:homepage' %}">Time2Meeting</a>
          <a class="btn btn-primary" href="{% url 'manage_event:index' %}">Sign In</a>
        {% endif %}
      </div>
    </nav>


    {% block main %}
    {% endblock %}

    <!-- Footer -->
    <footer class="footer bg-light">
      <div class="container">
        <div class="row">
          <div class="col-lg-6 h-100 text-center text-lg-left my-auto">
            <ul class="list-inline mb-2">
              <li class="list-inline-item">
                <a href="#">About</a>
              </li>
              <li class="list-inline-item">&sdot;</li>
              <li class="list-inline-item">
                <a href="{% url 'home:team' %}">Team</a>
              </li>
              <li class="list-inline-item">&sdot;</li>
              <li class="list-inline-item">
                <a href="#">Terms of Use</a>
              </li>
              <li class="list-inline-item">&sdot;</li>
              <li class="list-inline-item">
                <a href="#">Privacy Policy</a>
              </li>
            </ul>
            <p class="text-muted small mb-4 mb-lg-0">&copy; ColdCode 2017. All Rights Reserved.</p>
          </div>
          <div class="col-lg-6 h-100 text-center text-lg-right my-auto">
            <ul class="list-inline mb-0">
              <li class="list-inline-item mr-3">
                <a href="#">
                  <i class="fa fa-facebook fa-2x fa-fw"></i>
                </a>
              </li>
              <li class="list-inline-item mr-3">
                <a href="#">
                  <i class="fa fa-twitter fa-2x fa-fw"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <i class="fa fa-instagram fa-2x fa-fw"></i>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'home/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'home/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  </body>
</html>

home/templates/home/guidance.html
{% extends 'home/base.html' %}
{% load static %}
{% block main %}

  <header class="masthead text-white text-center">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-xl-9 mx-auto">
            <h1 class="mb-5">Simplify Scheduling. Reduce Chaos.</h1>
            <p class="mb-5">A one-stop scheduling web application focusing on lite groups’ demands and experiences.</p>
          </div>
          <div class="col-md-9 col-lg-8 col-xl-7 mx-auto">
            <form>
              <div class="form-row">
                <div class="col-0 col-md-4">
                </div>
                <div class="col-12 col-md-4">
                  <button type="submit" class="btn btn-block btn-lg btn-primary">Sign in!</button>
                </div>
                <div class="col-0 col-md-4">
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </header>

    <!-- Icons Grid -->
    <section class="features-icons bg-light text-center">
      <div class="container">
        <div class="row">
          <div class="col-lg-4">
            <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
              <div class="features-icons-icon d-flex">
                <i class="icon-screen-desktop m-auto text-primary"></i>
              </div>
              <h3>Scheduling Engine</h3>
              <p class="lead mb-0">Powerful scheduling engine to display overlap of time slots!</p>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
              <div class="features-icons-icon d-flex">
                <i class="icon-layers m-auto text-primary"></i>
              </div>
              <h3>Easy-used Calendar</h3>
              <p class="lead mb-0">Selecting whichever time slot with user friendly calendar.</p>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="features-icons-item mx-auto mb-0 mb-lg-3">
              <div class="features-icons-icon d-flex">
                <i class="icon-check m-auto text-primary"></i>
              </div>
              <h3>Real-time notifications</h3>
              <p class="lead mb-0">Ready to get notifications on all events and invitations!</p>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- Image Showcases -->
    <section class="showcase">
      <div class="container-fluid p-0">
        <div class="row no-gutters">

          <div class="col-lg-6 order-lg-2 text-white showcase-img" style="background-image: url('{% static 'home/img/bg-showcase-1.jpg' %}');"></div>
          <div class="col-lg-6 order-lg-1 my-auto showcase-text">
            <h2>One platform.</h2>
            <h2>Unlimited convenience.</h2>
            <p class="lead mb-0">When you use Time2Meeting, you can deal with all the scheduling tasks of the event with the platform, whether it's:</p>
            <p class="lead mb-0">• Select time slots</p>
            <p class="lead mb-0">• View event status</p>
            <p class="lead mb-0">• Make decision</p>
          </div>
        </div>
        <div class="row no-gutters">
          <div class="col-lg-6 text-white showcase-img" style="background-image: url('{% static 'home/img/bg-showcase-2.jpg' %}');"></div>
          <div class="col-lg-6 my-auto showcase-text">
            <h2>Click. Drag. Done.</h2>
            <p class="lead mb-0">Cloud scheduling software has never been easier. Use the most easy-used calendar create for humans to select time slots in a snap.</p>
            <p class="lead mb-0">• Half hour as a unit</p>
            <p class="lead mb-0">• Select as simple or complex as you need</p>
          </div>
        </div>
        <div class="row no-gutters">
          <div class="col-lg-6 order-lg-2 text-white showcase-img" style="background-image: url('{% static 'home/img/bg-showcase-3.jpg' %}');"></div>
          <div class="col-lg-6 order-lg-1 my-auto showcase-text">
            <h2>Every news.</h2>
            <h2>On Notification center.</h2>
            <p class="lead mb-0">Stop using spreadsheets and email to track events and skedules. Time2Meeting instantly shows you the progress of any news.</p>
            <p class="lead mb-0">• New invitation</p>
            <p class="lead mb-0">• Modification of events</p>
            <p class="lead mb-0">• Final decision on holding time</p>
          </div>
        </div>
      </div>
    </section>

    <!-- Testimonials -->
    <section class="testimonials text-center bg-light">
      <div class="container">
        <h2 class="mb-5">What people are saying...</h2>
        <div class="row">
          <div class="col-lg-4">
            <div class="testimonial-item mx-auto mb-5 mb-lg-0">
              <img class="img-fluid rounded-circle mb-3" src="{% static 'home/img/testimonials-1.jpg' %}" alt="">
              <h5>Margaret E.</h5>
              <p class="font-weight-light mb-0">"This is fantastic! Thanks so much guys!"</p>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="testimonial-item mx-auto mb-5 mb-lg-0">
              <img class="img-fluid rounded-circle mb-3" src="{% static 'home/img/testimonials-2.jpg' %}" alt="">
              <h5>Fred S.</h5>
              <p class="font-weight-light mb-0">"Bootstrap is amazing. I've been using it to create lots of super nice landing pages."</p>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="testimonial-item mx-auto mb-5 mb-lg-0">
              <img class="img-fluid rounded-circle mb-3" src="{% static 'home/img/testimonials-3.jpg' %}" alt="">
              <h5>Sarah	W.</h5>
              <p class="font-weight-light mb-0">"Thanks so much for making these free resources available to us!"</p>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- Call to Action -->
    <section class="call-to-action text-white text-center">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-xl-9 mx-auto">
            <h2 class="mb-4">Ready to get started? Sign up now!</h2>
          </div>
          <div class="col-md-10 col-lg-8 col-xl-7 mx-auto">
            <form>
              <div class="form-row">
                <div class="col-12 col-md-9 mb-2 mb-md-0">
                  <input type="email" class="form-control form-control-lg" placeholder="Enter your email...">
                </div>
                <div class="col-12 col-md-3">
                  <button type="submit" class="btn btn-block btn-lg btn-primary">Sign up!</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </section>

{% endblock%}

home/templates/home/homepage.html
{% extends 'home/base.html' %}
{% load static %}
{% block main %}

  <header class="masthead text-white text-center">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-xl-9 mx-auto">
            <h1 class="mb-5">Simplify Scheduling. Reduce Chaos.</h1>
            <p class="mb-5">A scheduling web application focused on <br>simplifying the process for lite groups to schedule events, meetings, appointments, etc.</p>
          </div>
          <div class="col-md-9 col-lg-8 col-xl-7 mx-auto">
            <form>
              <div class="form-row">
                <div class="col-0 col-md-4">
                </div>
                <div class="col-12 col-md-4">
                  <a class="btn btn-block btn-lg btn-primary" href="{% url 'manage_event:index' %}">Sign In</a>
                </div>
                <div class="col-0 col-md-4">
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </header>

    <!-- Icons Grid -->
    <section class="features-icons bg-light text-center">
      <div class="container">
        <div class="row">
          <div class="col-lg-4">
            <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
              <div class="features-icons-icon d-flex">
                <i class="icon-screen-desktop m-auto text-primary"></i>
              </div>
              <h3>Scheduling Engine</h3>
              <p class="lead mb-0">Powerful scheduling engine to find the best time of availability!</p>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
              <div class="features-icons-icon d-flex">
                <i class="icon-layers m-auto text-primary"></i>
              </div>
              <h3>Easy-to-use Calendar</h3>
              <p class="lead mb-0">Select whichever time slot you want with user friendly calendar.</p>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="features-icons-item mx-auto mb-0 mb-lg-3">
              <div class="features-icons-icon d-flex">
                <i class="icon-check m-auto text-primary"></i>
              </div>
              <h3>Real-time notifications</h3>
              <p class="lead mb-0">Ready to be updated on all events and invitations!</p>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- Image Showcases -->
    <section class="showcase">
      <div class="container-fluid p-0">
        <div class="row no-gutters">

          <div class="col-lg-6 order-lg-2 text-white showcase-img" style="background-image: url('{% static 'home/img/h1.png' %}');"></div>
          <div class="col-lg-6 order-lg-1 my-auto showcase-text">
            <h2>One platform.</h2>
            <h2>Unlimited convenience.</h2>
            <p class="lead mb-0">When you use Time2Meeting, you can deal with all the scheduling tasks of the event with the platform, whether it's:</p>
            <p class="lead mb-0">• Select time slots</p>
            <p class="lead mb-0">• View event status</p>
            <p class="lead mb-0">• Make decision</p>
          </div>
        </div>
        <div class="row no-gutters">
          <div class="col-lg-6 text-white showcase-img" style="background-image: url('{% static 'home/img/h2.png' %}');"></div>
          <div class="col-lg-6 my-auto showcase-text">
            <h2>Click. Drag. Done.</h2>
            <p class="lead mb-0">Online scheduling application has never been easier. Use the most easy-to-use calendar designed to select time slots in a snap.</p>
            <p class="lead mb-0">• Half hour as a unit</p>
            <p class="lead mb-0">• Select as simple or complex as you need</p>
          </div>
        </div>
        <div class="row no-gutters">
          <div class="col-lg-6 order-lg-2 text-white showcase-img" style="background-image: url('{% static 'home/img/h3.png' %}');"></div>
          <div class="col-lg-6 order-lg-1 my-auto showcase-text">
            <h2>Every news.</h2>
            <h2>On Notification center.</h2>
            <p class="lead mb-0">Stop using spreadsheets and emails to track events and schedules. Time2Meeting instantly shows you the progress of any news.</p>
            <p class="lead mb-0">• New invitation</p>
            <p class="lead mb-0">• Modification of events</p>
            <p class="lead mb-0">• Final decision on holding time</p>
          </div>
        </div>
      </div>
    </section>

    <!-- Testimonials -->
    <section class="testimonials text-center bg-light">
      <div class="container">
        <h2 class="mb-5"><a href="{% url 'home:team' %}">Who we are?</a></h2>
        <div class="row">
          <div class="col-lg-3">
            <div class="testimonial-item mx-auto mb-4 mb-lg-0">
              <a href="{% url 'home:team' %}"><img class="img-fluid rounded-circle mb-3" src="{% static 'home/img/yz.jpeg' %}" alt=""></a>
              <h5>Yi Zhang</h5>
            </div>
          </div>
          <div class="col-lg-3">
            <div class="testimonial-item mx-auto mb-5 mb-lg-0">
              <a href="{% url 'home:team' %}"><img class="img-fluid rounded-circle mb-3" src="{% static 'home/img/zdl.jpeg' %}" alt=""></a>
              <h5>Zhidong Liu</h5>
            </div>
          </div>
          <div class="col-lg-3">
            <div class="testimonial-item mx-auto mb-5 mb-lg-0">
              <a href="{% url 'home:team' %}"><img class="img-fluid rounded-circle mb-3" src="{% static 'home/img/yfz-1.jpeg' %}" alt=""></a>
              <h5>Yufeng Zhang</h5>
            </div>
          </div>
          <div class="col-lg-3">
            <div class="testimonial-item mx-auto mb-5 mb-lg-0">
              <a href="{% url 'home:team' %}"><img class="img-fluid rounded-circle mb-3" src="{% static 'home/img/qmh.jpeg' %}" alt=""></a>
              <h5>Qimeng Han</h5>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- Call to Action -->
    <section class="call-to-action text-white text-center">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-xl-9 mx-auto">
            <h2 class="mb-4">Ready to get started? Sign in now!</h2>
          </div>
          <div class="col-md-10 col-lg-8 col-xl-7 mx-auto">
            <form>
              <div class="form-row">
                <div class="col-0 col-md-4">
                </div>
                <div class="col-12 col-md-4">
                  <a class="btn btn-block btn-lg btn-primary" href="{% url 'manage_event:index' %}">Sign In</a>
                </div>
                <div class="col-0 col-md-4">
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </section>

{% endblock%}

home/templates/home/team.html
<!DOCTYPE html>
{% extends 'home/base.html' %}
{% load static %}
<html lang="en">
  {% block main %}
    <!-- Testimonials -->
  <body>
    <section class="testimonials text-center bg-light">
      <div class="container">
        <h2 class="mb-5">Who are we?</h2>
        <div class="row">
          <div class="col-lg-6">
            <div class="testimonial-item mx-auto mb-4 mb-lg-0">
              <img class="img-fluid rounded-circle mb-3" src="{% static 'home/img/yz.jpeg' %}" alt="">
              <h5>Yi Zhang</h5>
              <p class="font-weight-light mb-0">"This is fantastic! Thanks so much guys!"</p>
            </div>
          </div>
          <div class="col-lg-6">
            <div class="testimonial-item mx-auto mb-5 mb-lg-0">
              <img class="img-fluid rounded-circle mb-3" src="{% static 'home/img/zdl.jpeg' %}" alt="">
              <h5>Zhidong Liu</h5>
              <p class="font-weight-light mb-0">"Happy and learned a lot. I've created lots of super nice features with my teammates."</p>
            </div>
          </div>
          <div class="col-lg-6">
            <div class="testimonial-item mx-auto mb-5 mb-lg-0">
              <img class="img-fluid rounded-circle mb-3" src="{% static 'home/img/yfz-1.jpeg' %}" alt="">
              <h5>Yufeng Zhang</h5>
              <p class="font-weight-light mb-0">"Developing Time2Meeting is amazing. Love all you guys in ColdCode"</p>
            </div>
          </div>
          <div class="col-lg-6">
            <div class="testimonial-item mx-auto mb-5 mb-lg-0">
              <img class="img-fluid rounded-circle mb-3" src="{% static 'home/img/qmh.jpeg' %}" alt="">
              <h5>Qimeng Han</h5>
              <p class="font-weight-light mb-0">"I appreciate it so much for going through the agile development together with my teammates, unforgettable memory."</p>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- Image Showcases -->
    <section class="showcase">
      <div class="container-fluid p-0">
        <div class="row no-gutters">
          <div class="col-lg-6 order-lg-2 text-white showcase-img" style="background-image: url('{% static 'home/img/t1.jpeg' %}');"></div>
          <div class="col-lg-6 order-lg-1 my-auto showcase-text">
            <br>
            <h2>Summer</h2>
            <br>
            <p class="lead mb-0">Thanks to the first class, we teamed up as 'ColdCode', and began to discuss and sketch our web application.</p>
            <br>
            <p class="lead mb-0">• We decided to develop a scheduling web application for organizing meetings.</p>
            <p class="lead mb-0">• We came up with main features to implement by brainstorming user stories.</p>
            <p class="lead mb-0">• Our <a href="https://wireframe.cc/pro/pp/fa3b9b1d4116228#z01dllqr">wire-frames</a> then came out.</p>
            <br><br>
          </div>
        </div>
        <div class="row no-gutters">
          <div class="col-lg-6 text-white showcase-img" style="background-image: url('{% static 'home/img/t2.jpeg' %}');"></div>
          <div class="col-lg-6 my-auto showcase-text">
            <br>
            <h2>Fall</h2><br>
            <p class="lead mb-0">The 1st iteration of our project. We worked really hard day and night. 4AM library will always be in our memory of this project.</p>
            <br>
            <p class="lead mb-0">• We implemented the basic logic flow and framework.</p>
            <p class="lead mb-0">• Login module was achieved by using Google APi.</p>
            <p class="lead mb-0">• Creating events and selecting time slots worked out well.</p>
            <br><br>
          </div>
        </div>
        <div class="row no-gutters">
          <div class="col-lg-6 order-lg-2 text-white showcase-img" style="background-image: url('{% static 'home/img/t4.jpeg' %}');"></div>
          <div class="col-lg-6 order-lg-1 my-auto showcase-text">
            <br>
            <h2>Winter</h2><br>
            <p class="lead mb-0">Time flies and we went on fighting for the 2nd Iteration. Although temperature keeps going down everyday, our passion has never decreased.</p>
            <br>
            <p class="lead mb-0">• New feature: organizers can make decisions.</p>
            <p class="lead mb-0">• Notification center & email invitation are now achieved</p>
            <p class="lead mb-0">• UI was greatly improved and that is not the ending point :).</p>
            <br><br>
          </div>
        </div>
        <div class="row no-gutters">
          <div class="col-lg-6 text-white showcase-img" style="background-image: url('{% static 'home/img/t5.jpeg' %}');"></div>
          <div class="col-lg-6 my-auto showcase-text">
            <br>
            <h2>Stories: J.P.Morgan</h2><br>
            <p class="lead mb-0">Our course collaborates with J.P.Morgan, with whom we had the most enjoyable and unforgettable experiences.</p>
            <br>
            <p class="lead mb-0">• At the end of 2017, we set up our booth at J.P.Morgan, selling Time2Meeting to all of the judges and guests.</p>
            <p class="lead mb-0">• Truly thanks to our lovely mentor, Justin, a considerate and energetic man who has shared plenty of inspiring ideas and keeps motivating us to move forward.</p>
            <br><br>
          </div>
        </div>
      </div>
    </section>

  </body>

  {% endblock%}
</html>