home/urls.py
from django.conf.urls import url

from . import views

app_name = 'home'

urlpatterns = [
    url(r'^homepage/$', views.homepage, name='homepage'),
    url(r'^guidance/$', views.guidance, name='guidance'),
    url(r'^team/$', views.team, name='team'),
]

manage_event/urls.py
from django.conf.urls import url
from . import views

app_name = 'manage_event'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^organize/$', views.organize_index, name='organize_index'),
    url(r'^participate/$', views.participate_index, name='participate_index'),

    url(r'^(?P<event_id>[0-9]+)/notification_redirect/(?P<notification_id>[0-9]+)/$', views.notification_redirect, name='notification_redirect'),
    url(r'^(?P<event_id>[0-9]+)/on_going/$', views.on_going, name='on_going'),
    url(r'^(?P<event_id>[0-9]+)/pending/$', views.pending, name='pending'),

    url(r'^(?P<event_id>[0-9]+)/make_decision/$', views.make_decision, name='make_decision'),
    url(r'^(?P<event_id>[0-9]+)/make_decision_render/$', views.make_decision_render, name='make_decision_render'),
    url(r'^(?P<event_id>[0-9]+)/make_decision_results/$', views.make_decision_results, name='make_decision_results'),
    url(r'^(?P<event_id>[0-9]+)/make_decision_detail/$', views.make_decision_detail, name='make_decision_detail'),
    url(r'^(?P<event_id>[0-9]+)/show_decision_result/$', views.show_decision_result, name='show_decision_result'),
    url(r'^(?P<event_id>[0-9]+)/abort_event_detail/$', views.abort_event_detail, name='abort_event_detail'),
    url(r'^(?P<event_id>[0-9]+)/abort_event_result/$', views.abort_event_result, name='abort_event_result'),
    url(r'^(?P<event_id>[0-9]+)/modify_event_deadline_detail/$', views.modify_event_deadline_detail, name='modify_event_deadline_detail'),
    url(r'^(?P<event_id>[0-9]+)/modify_event_deadline_result/$', views.modify_event_deadline_result, name='modify_event_deadline_result'),

    url(r'^create_event/$', views.create_event, name='create_event'),
    url(r'^(?P<event_id>[0-9]+)/create_publish/$', views.create_publish, name='create_publish'),
    url(r'^(?P<event_id>[0-9]+)/select_timeslots/$', views.select_timeslots, name='select_timeslots'),
    url(r'^(?P<event_id>[0-9]+)/modify_timeslots/$', views.modify_timeslots, name='modify_timeslots'),
    url(r'^profile/$', views.update_profile),
    url(r'^logout/$', views.webLogout),
    url(r'^(?P<event_id>[0-9]+)/select_publish/$', views.select_publish, name="select_publish"),
    url(r'^(?P<event_id>[0-9]+)/modify_timeslots_read/$', views.modify_timeslots_read, name="modify_timeslots_read"),
    url(r'^(?P<event_id>[0-9]+)/read_timeslots/$', views.read_timeslots, name='read_timeslots'),


    url(r'^(?P<event_id>[0-9]+)/make_decision_json/$', views.make_decision_json, name='make_decision_json'),

    url(r'^(?P<event_id>[0-9]+)/initialize_timeslots/$', views.initialize_timeslots, name='initialize_timeslots'),
    url(r'^(?P<event_id>[0-9]+)/modify_timeslots_update/$', views.modify_timeslots_update, name='modify_timeslots_update'),
    url(r'^(?P<event_id>[0-9]+)/select_publish_render/$', views.select_publish_render, name="select_publish_render"),
    url(r'^accept_invitation/(?P<key>\w+)/$', views.accept_invitation, name="accept_invitation"),
    url(r'^decline_invitation/(?P<key>\w+)/$', views.decline_invitation, name="decline_invitation"),

]

mysite/urls.py
import notifications.urls
from django.conf.urls import include, url
from django.contrib import admin
from home import views

urlpatterns = [
    url(r'^manage_event/', include('manage_event.urls')),
    url(r'^admin/', admin.site.urls),
    # This is our homepage!
    url(r'^$', views.homepage),
    url(r'^home/', include('home.urls')),
    url(r'^account/', include('social_django.urls', namespace='social')),
    url(r'^account/', include('django.contrib.auth.urls', namespace='auth')),
    url(r'^inbox/notifications/', include(notifications.urls, namespace='notifications')),

]

manage_event/models.py
import datetime
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.crypto import get_random_string


class Profile(models.Model):
    """
    Module for profile.
    """
    user = models.OneToOneField(User, unique=True, null=False, db_index=True)
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    """
    Create user profile.
    """
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    """
    Save user profile.
    """
    instance.profile.save()


class Events(models.Model):
    """
    Module for events table.
    """
    event_name = models.CharField(max_length=300, blank=False)
    create_time = models.DateTimeField(default=datetime.datetime.now)
    time_range_start = models.DateTimeField(blank=False)
    time_range_end = models.DateTimeField()
    final_time_start = models.DateTimeField(null=True, blank=True)
    final_time_end = models.DateTimeField(null=True, blank=True)
    deadline = models.DateTimeField()
    duration = models.DurationField()

    # record the status of the event, "Available' or 'Abort'
    status = models.CharField(max_length=10, default='Available')
    info = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.event_name


class AbortMessage(models.Model):
    """
    Module for abort message table.
    """
    event = models.ForeignKey(Events, on_delete=models.CASCADE)
    Abort_message = models.TextField(null=True, blank=True)


class EventUser(models.Model):
    """
    Module for eventuser table, which is used for record role of user.
    """
    event = models.ForeignKey(Events, on_delete=models.CASCADE)
    user = models.ForeignKey(User, null=True)

    class Meta:
        unique_together = ("event", "user")

    # two roles: "O" for organizer, "P" for participant
    USER_ROLE = (
        ('o', 'Organizer'),
        ('p', 'Participant'),
    )
    role = models.CharField(max_length=1, choices=USER_ROLE, default='p')


class TimeSlots(models.Model):
    """
    Module for time slots table.
    """
    event = models.ForeignKey(Events, on_delete=models.CASCADE)
    user = models.ForeignKey(User, null=True)
    time_slot_start = models.DateTimeField()

    class Meta:
        unique_together = ("event", "user", "time_slot_start")


class Invitation(models.Model):
    """
    Model for invitations.
    """
    email = models.EmailField(max_length=254)
    event = models.ForeignKey(Events)
    inviter = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    key = models.CharField(max_length=64, unique=True)
    created = models.DateTimeField(default=datetime.datetime.now)
    confirmed = models.BooleanField(default=False)

    @classmethod
    def create(cls, event, mail_list, inviter=None):
        insert_list = []
        for mail in mail_list:
            key = get_random_string(64).lower()
            insert_list.append(Invitation(email=mail, event=event, key=key, inviter=inviter))
        instances = cls.objects.bulk_create(insert_list)
        return instances

manage_event/views.py
import datetime
import json
import sys
import re
from django.views import generic
from django.utils import timezone
from .models import Profile
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import logout
from django.db import transaction
from .forms import UserForm, ProfileForm, EventForm, InvitationForm, AbortForm, DeadlineForm
from .models import Events, TimeSlots, EventUser, AbortMessage, Invitation
from notifications.models import Notification
from notifications.signals import notify
from django.contrib import messages
from django.utils.translation import ugettext_lazy as _
from django.db.models import Q
from django.core.mail import send_mail
from django.conf import settings
from django.template.loader import render_to_string
import functools


@login_required
def index(request):
    """
    Basic index page after user log in.
    :param request:
    :return:
    """
    user = request.user
    notifications = user.notifications.read()

    return render(request, 'manage_event/index.html', {
        'notifications': notifications,
    })


@login_required
def notification_redirect(request, event_id, notification_id):
    """
    Used for make notification as read and redirect to corresponding pages.
    :param request:
    :param event_id:
    :param notification_id:
    :return:
    """
    event = get_object_or_404(Events, pk=event_id)
    notification = get_object_or_404(Notification, pk=notification_id)
    notification.mark_as_read()
    if notification.verb == 'aborted event' or notification.verb == 'decided final time on event':
        return HttpResponseRedirect(reverse('manage_event:show_decision_result', args=(event_id,)))
    elif notification.verb == 'modified event':
        return HttpResponseRedirect(reverse('manage_event:modify_timeslots', args=(event_id,)))
    else:
        obj = Invitation.objects.filter(event=event).filter(email=request.user.email).first()
        accept_invite_url = reverse('manage_event:accept_invitation', args=[obj.key])
        decline_invite_url = reverse('manage_event:decline_invitation', args=[obj.key])
        accept_invite_url = request.build_absolute_uri(accept_invite_url)
        decline_invite_url = request.build_absolute_uri(decline_invite_url)
        return render(request, 'manage_event/invite_confirm.html', {
            'event': event,
            'accept_invite_url': accept_invite_url,
            'decline_invite_url': decline_invite_url
        })


@login_required
def organize_index(request):
    """
    Organize index page.
    :param request:
    :return:
    """
    # print(request.user.email)
    organized_events = EventUser.objects.filter(user=request.user).filter(role="o")
    organized_events_id = []

    for organized_event in organized_events:
        organized_events_id.append(organized_event.event.id)

    event_wait_for_decision = Events.objects.filter(Q(id__in=organized_events_id),
                                                    Q(status='Available'),
                                                    Q(final_time_start__isnull=True),
                                                    Q(deadline__lte=datetime.datetime.now())).order_by('-create_time')
    event_on_going = Events.objects.filter(Q(id__in=organized_events_id),
                                           Q(status='Available'),
                                           Q(deadline__gte=datetime.datetime.now())).order_by('-create_time')
    event_history = Events.objects.filter(Q(id__in=organized_events_id),
                                          Q(final_time_start__isnull=False) | Q(status='Abort')).order_by('-create_time')
    # latest_event_list = Events.objects.order_by('-event_date')[:5]
    # output = ', '.join([q.event_name for q in latest_event_list])
    return render(request, 'manage_event/organize_index.html', {
        'event_wait_for_decision': event_wait_for_decision,
        'event_on_going': event_on_going,
        'event_history': event_history
    })


@login_required
def participate_index(request):
    """
    Participate index page.
    :param request:
    :return:
    """

    participate_events = EventUser.objects.filter(user=request.user)
    participate_events_id = []
    for participate_event in participate_events:
        participate_events_id.append(participate_event.event.id)

    to_do_events_id = []
    done_events_id = []
    for participate_event_id in participate_events_id:
        if TimeSlots.objects.filter(user=request.user).filter(event_id=participate_event_id).count() == 0:
            to_do_events_id.append(participate_event_id)
        else:
            done_events_id.append(participate_event_id)

    event_to_do = Events.objects.filter(Q(id__in=to_do_events_id),
                                        Q(status='Available'),
                                        Q(deadline__gte=datetime.datetime.now())).order_by('-create_time')
    event_done = Events.objects.filter(Q(id__in=done_events_id),
                                       Q(status='Available'),
                                       Q(deadline__gte=datetime.datetime.now())).order_by('-create_time')
    event_result = Events.objects.filter(Q(id__in=participate_events_id),
                                         Q(final_time_start__isnull=False) | Q(status='Abort')).order_by('-create_time')
    event_pending = Events.objects.filter(Q(id__in=participate_events_id),
                                          Q(status='Available'),
                                          Q(deadline__lte=datetime.datetime.now())).exclude(final_time_start__isnull=False).order_by('-create_time')
    # latest_event_list = Events.objects.order_by('-event_date')[:5]
    # output = ', '.join([q.event_name for q in latest_event_list])
    return render(request, 'manage_event/participate_index.html', {
        'event_to_do': event_to_do,
        'event_done': event_done,
        'event_result': event_result,
        'event_pending': event_pending,
    })


@login_required
def create_event(request):
    """
    Create event page.
    :param request:
    :return:
    """
    if request.method == 'POST':
        form = EventForm(request.POST)
        if form.is_valid():
            event_data = form.cleaned_data
            event = Events.objects.create(**event_data)
            event.save()

            # create corresponding EventUser tuple.
            eventuser_data = {'event': event,
                              'user': request.user,
                              'role': 'o'}
            eventuser = EventUser.objects.create(**eventuser_data)
            eventuser.save()
            return HttpResponseRedirect(reverse('manage_event:create_publish', args=(event.id,)))
    else:
        form = EventForm()
    return render(request, 'manage_event/create_event.html', {'form': form})


@login_required
#@permission_required(role='o')
def modify_event_deadline_detail(request, event_id):
    """
    Modify event deadline and overwrite the datebase.
    :param request:
    :return:
    """
    event = get_object_or_404(Events, pk=event_id)
    #if EventUser.objects.get(event=event, user=request.user).role == 'o':
    if request.method == 'POST':
        form = DeadlineForm(request.POST, instance = event)
        if form.is_valid():
            modified_deadline = form.cleaned_data.get('deadline')
            event.deadline = modified_deadline
            event.save()
            return HttpResponseRedirect(reverse('manage_event:modify_event_deadline_result', args=(event_id,)))
    else:
        form = DeadlineForm()
        contents = {'event': event,
                    'message': "Cautious: Every participants will be notified about the change of submisson deadline."}
#else:
        #contents = {'event': event, 'error_message': "Sorry, you didn't have the access to modify the deadline of this event."}
    return render(request, 'manage_event/modify_event_deadline_detail.html', {'form': form})


def modify_event_deadline_result(request, event_id):
    event = get_object_or_404(Events, pk=event_id)

    # send notifications to all the participants
    notify.send(sender=request.user,
                recipient=[eventuser.user for eventuser in EventUser.objects.filter(event=event)],
                verb='modified event',
                target=event,
                description=event.id,
                timestamp=datetime.datetime.now().replace(microsecond=0))
    context = {'event': event}
    return render(request, 'manage_event/modify_event_deadline_result.html', context)


def send_invitation(request, event, objs):
    current_site = request.get_host()
    inviter = request.user.first_name + ' ' + request.user.last_name
    event_name = event.event_name

    for obj in objs:
        accept_invite_url = reverse('manage_event:accept_invitation', args=(obj.key,))
        decline_invite_url = reverse('manage_event:decline_invitation', args=(obj.key,))
        accept_invite_url = request.build_absolute_uri(accept_invite_url)
        decline_invite_url = request.build_absolute_uri(decline_invite_url)

        context = {
            'site_name': current_site,
            'inviter': inviter,
            'event_name': event_name,
            'accept_invite_url': accept_invite_url,
            'decline_invite_url': decline_invite_url,
        }

        msg_html = render_to_string('invitations/email/email_invite_message.html', context)
        msg_plain = render_to_string('invitations/email/email_invite_message.txt', context)
        sub_plain = render_to_string('invitations/email/email_invite_subject.txt', context)

        send_mail(sub_plain,
                  msg_plain,
                  settings.EMAIL_HOST_USER,

manage_event/templates/manage_event/abort_event_detail.html
{% extends 'manage_event/sidebar.html' %}
{% block content %}

<h1>Aborting event: {{ event.event_name }}</h1>
{% if message %}
<h4><strong>{{ message }}</strong></h4>

<form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" class="btn btn-danger" value="Abort">
</form>

<br>
<button class="btn btn-primary" onclick="location.href='{% url 'manage_event:organize_index' %}'">Back to Organize Events</button>

{% endif %}

{% endblock%}

manage_event/templates/manage_event/abort_event_result.html
{% extends 'manage_event/sidebar.html' %}
{% block content %}

<div align="center">
<h1>{{ event.event_name }}</h1>

<h4> You have aborted this event. Your message left by you has informed of each participant.</h4>
    <p>Message:</p>
    <p>{{ message }}</p>

<a class="btn btn-primary" href="{% url 'manage_event:organize_index' %}" role="button">Back to Organize Event</a>
</div>

{% endblock%}

manage_event/templates/manage_event/create_publish.html
{% extends 'manage_event/sidebar.html' %}
{% block content %}
<div align="center">
    <h1>Event Created Successfully!</h1>
</div>

<div class="row">
    <div class="col-lg-3 "></div>
    <div class="col-lg-6">
        <h4>Type in emails to invite your friends to join the event:</h4>

        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li {% if message.tags %} class="{{ message.tags }}" {% endif %} >
                {{ message }}
            </li>
            {% endfor %}
        </ul>
        {% endif %}

        <div >
            <form method="post">
                {% csrf_token %}
                {{ form }}
                <br>
                <input type="submit" class = "btn btn-primary"  value="Invite">
            </form>
        </div>
    </div>

    <div class="col-lg-3 ">
        <h4>Contact<i>(Copy to use)</i></h4>
        <div style="height:115px;border:1px solid #ccc;background-color:white;overflow:auto;">
            {% for contact in contacts %}
                {{contact}}
                <br>
            {% endfor %}
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-3 ">
    </div>
    <div class="col-lg-6">
        <br><br>
    <button class = "btn btn-warning" onclick="location.href='{% url 'manage_event:select_timeslots' event_id %}'">Select your time slots</button>
    <button class = "btn btn-primary" onclick="location.href='{% url 'manage_event:organize_index' %}'">Back to organize events</button>

    </div>
</div>


{% endblock%}

manage_event/templates/manage_event/make_decision.html
{% extends 'manage_event/calendar.html' %}


{% block head %}
<h1>{{ event.event_name }}</h1>
<h4>Please make a decision for this event.</h4>
    <table class="table table-hover table-bordered">
        <tr>
            <th scope="row">Created time</th>
            <td>{{ event.create_time }}</td>
        </tr>
        <tr>
            <th scope="row">Time range</th>
            <td>{{ event.time_range_start }} to {{ event.time_range_end }}</td>
        </tr>
        <tr>
            <th scope="row">Duration</th>
            <td>{{ event.duration }}</td>
        </tr>
        <tr>
            <th scope="row">Deadline</th>
            <td>{{ event.deadline }}</td>
        </tr>
        {% if event.info %}
        <tr>
            <th scope="row">Info</th>
            <td>{{ event.info }}</td>
        </tr>
        {% endif %}
    </table>

{% endblock %}


{% block jsAndButton %}
<script type="text/javascript" charset="utf-8">
    loadTimeSlotsAndCreateTimeTable("../make_decision_json", "marked");
</script>
<br>
<button type="button" class="btn btn-success"onclick="postTimeSlotsAndRedirect('../make_decision/','../make_decision_render')">Make Decision</button>
<button type="button" class="btn btn-primary" onclick="location.href='{% url 'manage_event:modify_event_deadline_detail' event.id %}'">Modify Deadline</button>
<button type="button" class="btn btn-warning" onclick="location.href='{% url 'manage_event:abort_event_detail' event.id %}'">Abort Event</button>
<br><br>
{% endblock %}

manage_event/templates/manage_event/make_decision_results.html
{% extends 'manage_event/sidebar.html' %}
{% block content %}


<div align="center">
<h1>{{ event.event_name }}</h1>
    <h4> You chose <b>{{ event.final_time_start }}</b> to <b>{{ event.final_time_end }}</b> as the final holding time.</h4>

<a class="btn btn-primary"  href="{% url 'manage_event:organize_index' %}" role="button">Back to Organize Event</a>
{% if can_abort %}
    <button type="button" class="btn btn-warning" onclick="location.href='{% url 'manage_event:abort_event_detail' event.id %}'">Abort Event</button>
<br>
{% endif %}
<br><br>
</div>


{% endblock%}

manage_event/templates/manage_event/modify_event_deadline_detail.html
{% extends 'manage_event/sidebar.html' %}
{% block content %}
{{ form.media }}

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags }}" {% endif %} >
        {{ message }}
    </li>
    {% endfor %}
</ul>
{% endif %}

<div class="row">
<div class="col-lg-3"></div>
<div class="col-lg-6">
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-primary" value="Modify the Event Deadline">
</form>
    <button class="btn btn-primary" onclick="location.href='{% url 'manage_event:organize_index' %}'">Back to Organize Events</button>
</div>
</div>

{% endblock%}

manage_event/templates/manage_event/organize_index.html
{% extends 'manage_event/sidebar.html' %}
{% load static %}
{% load my_tags %}
{% block content %}

<style type="text/css">

.col-md-3 {
    border: 10px solid none;
    display: inline-block;
    padding: 7px;
}

.flip-container {
    perspective: 1000px;
}

.cardHeader {
    color: #FFFFFF;
    font-style: italic;
    font-size: 25px;
}

.cardContext {
    color: #FFFFFF;
    font-style: italic;
}

/* flip the pane when hovered */

.flip-container:hover .flipper,
.flip-container.hover .flipper {
    -webkit-transform: rotateY(180deg);
    transform: rotateY(180deg);
}

.flip-container,
.front,
.back {
    width: 100%;
    height: 150px;
}

.flip-container,
.front-low,
.back {
    width: 100%;
    height: 150px;
}

.image {
    zoom: 60%;
    opacity: 0.7;
    filter: alpha(opacity=40);

}

.image:hover {
    transform: scale(1.1, 1.1);
    transition: 0.2s ease;
}




/* flip speed goes here */

.flipper {
    -webkit-transition: 0.6s;
    transition: 0.6s;
    transform-style: preserve-3d;
    -webkit-transform-style: preserve-3d;
    -moz-transform-style: preserve-3d;
    -o-transform-style: preserve-3d;
    -ms-transform-style: preserve-3d;

    position: relative;
}

.front,
.back {
    -webkit-backface-visibility: hidden;
    backface-visibility: hidden;
    position: absolute;
    top: 0;
    left: 0;
}

.front-low,
.back {
    -webkit-backface-visibility: hidden;
    backface-visibility: hidden;
    position: absolute;
    top: 0;
    left: 0;
}

/* front pane, placed above back */

.front {
    padding: 10px;
    -webkit-transform: rotateY(0deg);
    transform: rotateY(0deg);
    background: #8fbfef;
}

.front-low {
    padding: 10px;
    -webkit-transform: rotateY(0deg);
    transform: rotateY(0deg);
    background: #cccccc;
}

/* back, initially hidden pane */

.back {
    padding: 10px;
    background: #f7a855;
    -webkit-transform: rotateY(180deg);
    transform: rotateY(180deg);
}

</style>
<style>
    .sectionTitle {
    font-family: Impact;
    font-size: 25px;
    }
    .sectionTitleCreate {
    font-family: Impact;
    font-size: 25px;
    color: #f7a855;
    }
</style>

<div>
            <div class="tab-content " id="TabContent">

                <div id="newEvent" class="anchor">
                    <div class="sectionTitle">Create New Event</div>
                    <div class="row">
                        <div class="col-md-3">
                            <a href='{% url "manage_event:create_event" %}'>
                                <div >
                                     &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<img class="image" src="{% static 'manage_event/3.png' %}">
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
                <br><br>
                <div id="waitForDecision" class="anchor">
                    <div class="sectionTitle">To Decide</div>
                    {% for event in event_wait_for_decision %} {% if forloop.counter|modulo:4 == 1 %}
                    <div class="row">
                        {% endif %}
                        <div class="col-md-3">
                            <a href="{% url 'manage_event:make_decision_detail' event.id%}">
                            <div class="flip-container alphas" ontouchstart="this.classList.toggle('hover');">
                                <div class="flipper">
                                    <div class="front">
                                        <p class="cardHeader">{{event.event_name}}</p>
                                        <p class="cardContext">{{event.create_time}}</p>
                                    </div>
                                    <div class="back">
                                        <p class="cardContext">Time range: {{ event.time_range_start }} to {{ event.time_range_end }}</p>
                                        <p class="cardContext">Duration: {{ event.duration }}</p>
                                        <p class="cardContext">Deadline: {{ event.deadline }}</p>
                                        <p class="cardContext">{{ event.info }}</p>
                                    </div>
                                </div>
                            </div>
                                </a>
                        </div>
                        {% if forloop.last or forloop.counter|modulo:4 == 0 %}
                    </div>
                    {% endif %}
                    {% endfor %}
                    <div class="row">
                         <div class="col-md-3">
                            <div class="flip-container alphas" ontouchstart="this.classList.toggle('hover');">
                            </div>
                        </div>
                    </div>
                </div>
                <div id="ongoing" class="anchor">
                    <div class="sectionTitle">In Progress</div>
                    {% for event in event_on_going %} {% if forloop.counter|modulo:4 == 1 %}
                    <div class="row">
                        {% endif %}
                        <div class="col-md-3">
                            <a href="{% url 'manage_event:on_going' event.id%}">
                            <div class="flip-container alphas" ontouchstart="this.classList.toggle('hover');">
                                <div class="flipper">
                                    <div class="front">
                                        <p class="cardHeader">{{event.event_name}}</p>
                                        <p class="cardContext">{{event.create_time}}</p>
                                    </div>
                                    <div class="back">
                                        <p class="cardContext">Time range: {{ event.time_range_start }} to {{ event.time_range_end }}</p>
                                        <p class="cardContext">Duration: {{ event.duration }}</p>
                                        <p class="cardContext">Deadline: {{ event.deadline }}</p>
                                        <p class="cardContext">{{ event.info }}</p>
                                    </div>
                                </div>
                            </div>
                            </a>
                        </div>
                        {% if forloop.last or forloop.counter|modulo:4 == 0 %}
                    </div>
                    {% endif %}
                    {% endfor %}
                    <div class="row">
                         <div class="col-md-3">
                            <div class="flip-container alphas" ontouchstart="this.classList.toggle('hover');">
                            </div>
                        </div>
                    </div>
                </div>
                <div id="history" class="anchor">
                   <div class="sectionTitle">History</div>

                    {% for event in event_history %} {% if forloop.counter|modulo:4 == 1 %}
                    <div class="row">
                        {% endif %}
                        <div class="col-md-3">
                            <a href="{% url 'manage_event:make_decision_results' event.id%}">
                            <div class="flip-container alphas" ontouchstart="this.classList.toggle('hover');">
                                <div class="flipper">
                                    <div class="front-low">
                                        <p class="cardHeader">{{event.event_name}}</p>
                                        <p class="cardContext">{{event.create_time}}</p>
                                    </div>
                                    <div class="back">
                                        <p class="cardContext">Time range: {{ event.time_range_start }} to {{ event.time_range_end }}</p>
                                        <p class="cardContext">Duration: {{ event.duration }}</p>
                                        <p class="cardContext">Deadline: {{ event.deadline }}</p>
                                        <p class="cardContext">{{ event.info }}</p>
                                    </div>
                                </div>
                            </div>
                            </a>
                        </div>
                        {% if forloop.last or forloop.counter|modulo:4 == 0 %}
                    </div>
                    {% endif %}
                    {% endfor %}
                    <div class="row">
                         <div class="col-md-3">
                            <div class="flip-container alphas" ontouchstart="this.classList.toggle('hover');">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
</div>
    {% endblock%}